name: etrace
base: bare
# build-base of core20 ensures we have the newest version of build-packages such
# as git
build-base: core20
adopt-info: etrace
summary: etrace traces programs for debugging or performance analysis
description: |
  etrace is a utility like strace or ltrace which uses ptrace to follow 
  programs executed by a main program for performance and debugging analysis. It
  also supports limited tracing of file accesses for analyzing what files a
  program accesses during it's execution.

grade: stable
confinement: classic

apps:
  etrace:
    command: bin/etrace

parts:
  etrace:
    # we want static builds
    build-environment:
      - CGO_ENABLED: "0"
    # we need git for setting the version
    build-packages:
      - git
    plugin: go
    source: .
    # we override the build to do just the first step, the go plugin currently
    # always will manually link the executables which forces the binaries to
    # need libc, which we don't need if we set CGO_ENABLED=0
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cd $SNAPCRAFT_PART_SRC
      go build -o $SNAPCRAFT_PART_INSTALL/bin ./...
    override-prime: |
      set -e
      snapcraftctl prime
      cd $SNAPCRAFT_PART_SRC
      echo "version is being set to $(git describe --tags --always --dirty)"
      snapcraftctl set-version $(git describe --tags --always --dirty)
